name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Vet
        run: go vet -v ./...

      - name: Test
        run: go test -v -count=1 ./...